### ISSUE TITLE
Switch to a geometry backend

### ISSUE THREAD

**Issue by mileslucas** [JuliaAstro/Photometry.jl#22]
After spending many hours trying to patch together some code for doing exact overlaps of rectangular apertures, I've decided _there has to be a better way_. I think there is.

I think there is a way to **substantially** cut down on the code required for calculating overlaps for aperture photometry by leveraging the code from some JuliaGeometry packages. 

## The general problems
* Area of overlap of an arbitrary ellipse (position, semi-major axis, semi-minor axis, position angle) with an axis-aligned rectangle
This includes the special case of a circle

* Area of overlap of an arbitrary polygon (points) with an axis-aligned rectangle
This includes the special case of an arbitrary rectangle (position, width, height, position angle)

## Current Implementation

Currently, we only support circular and elliptical overlap, but I'd like to support rectangles and polygons, too. The method for circular and elliptical is some modified version of the Sutherland-Hodgman algorithm. For the circular version, its simple enough to find intersections with the circle and compose the area using triangles and chords. 

For the elliptical, we use the transform for the ellipse into the unit circle and apply that to the rectangle's points. This creates a parallelogram (not axis-aligned) which we break into two triangles. These triangles are then fed through a modified Sutherland-Hodgman for their overlap with the unit circle. 

## Call for help

Performance is important, but I'm more considered about usability and coverage of different geometric types. This is why I think this can be made better using another package, but I don't really know how to use them for this purpose. The point between where we do calculations and transforming our data into geometry types for outsourcing the calculations is also not clear to me (e.g. is it better/faster to calculate area overlap of two triangles and unit-circle or a polygon and unit-circle?)

If there is anyone who can help me find a way to achieve this, I would greatly appreciate it.

**Comment by mileslucas** [comment]
@mforets has shown the great usage of `LazySets.jl` for this task. We ought to be able to rewrite a lot of the `overlap.jl` code using those tools (and probably gain speed, too). 

This would be good to accomplish in parallel to any development of new features.

**Comment by mforets** [comment]
> @mforets has shown the great usage of LazySets.jl for this task

:+1:  I've [re-written the notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week11/2D_intersection.ipynb) adding text and examples. (Note that you need at least LazySets v1.32.1 to run it.)

Feel free to open issues in LazySets if you have questions!

**Comment by mileslucas** [comment]
Currently the aperture photometry code is stable and performant enough for my wants, so I’m going to close this. 

With that being said, I still think it is a good idea given more advancement from the geometry packages in terms of API.
