### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by mileslucas** [JuliaAstro/Photometry.jl#3]
@JuliaRegistrator register

**Comment by mileslucas** [comment]
@JuliaRegistrator register

**Comment by mileslucas** [comment]
@JuliaRegistrator register

**Comment by mileslucas** [comment]
@JuliaRegistrator register

**Comment by mileslucas** [comment]
@JuliaRegistrator register

**Comment by mileslucas** [comment]
@JuliaRegistrator  register

**Comment by giordano** [comment]
Do you know that you can just comment on the commit instead of using an issue? :wink:
