### ISSUE TITLE
Redundant calling of bbox for circular aperture

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaAstro/Photometry.jl#6]
https://github.com/JuliaAstro/Photometry.jl/blob/46d4a6c85849c63737a9a7e61e8393e8b7356dbd/src/Aperture/circular.jl#L44

Line number 43: creating bounds by calling edges, and edges call bbox internally.
Line number 44: creating a bounding box by calling bbox
Line number 45: getting size, size calls bbox internally
Line number 46: calling circular_overlap but there is no use of the variable created in line 44, because it is not being passed as an argument.

Similarly at https://github.com/JuliaAstro/Photometry.jl/blob/46d4a6c85849c63737a9a7e61e8393e8b7356dbd/src/Aperture/circular.jl#L90

**Comment by siddharthlal25** [comment]
Update: When locally tested all the tests pass without line 44 and line 90

**Comment by mileslucas** [comment]
Closed via #7
